name: Use Composite Action

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Custom Action
        uses: ./.github/actions/setup-and-greet
        with:
          name: "Karina"
          language: "en"