name: Conditionals Demo

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Run only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "Running on main branch"

      - name: Intentional Failure
        id: fail_step
        run: exit 1
        continue-on-error: true

      - name: Runs if previous step failed
        if: failure()
        run: echo "Previous step failed"