name: First Workflow

on:
push:
branches:
- main
- master

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: greets user
        run: echo "Hello from GitHub Actions!" 

      - name: print current date and time
        run : date
   
      - name: Printing name of the branch that triggered the workflow
        run: echo "Branch:" ${{ github.ref_name }}

      - name: Listing files in the repo
        run: ls -la
         
      - name: printing Runner's operating system
        run: echo "Runner OS:" ${{ runner.os }}