name: First Workflow

on:
push:
branches:
- main
- master

jobs:
greet:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Say Hello
    run: echo "Hello from GitHub Actions!"

  - name: Print Date
    run: date

  - name: Show Branch Name
    run: echo "Branch: ${{ github.ref_name }}"

  - name: List Files
    run: ls -la

  - name: Show OS
    run: uname -a
```
