name: cron schedule
on:
  workflow_dispatch: 
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight
jobs:
    scheduled-job:
        runs-on: ubuntu-latest
        steps:
            - name: print time
              run: date
            - name: print cpu usage
              run : ps -aux | grep -i "cpu"