name: Secrets Demo

on: push

jobs:
  secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: false"
          else
            echo "The secret is set: true"
          fi

      - name: Try printing secret
        run: echo "Secret value is ${{ secrets.MY_SECRET_MESSAGE }}"