name: Secrets Demo

on: push

jobs:
  secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret as Env
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "Using username: $USERNAME"