name: Secrets Demo

on: workflow_dispatch

jobs:
  secret-job:
    runs-on: ubuntu-latest
    environment: DOCKER_USERNAME   

    steps:
      - name: Use Secret as Env
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "Using username: $USERNAME"