name: Smart Triggers

on:
  push:
    branches:
      - main
      - 'release/*'
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Code changed in src/app"